-- 0002_vehicle_trims_fitment.sql
-- Add trim/modification-aware fitment caching

-- Vehicle modifications (Wheel-Size "modifications" a.k.a. trims)
create table if not exists vehicle_modification (
  id                uuid primary key,
  vehicle_id        uuid not null references vehicle(id) on delete cascade,
  -- Wheel-Size modification slug/id (stable identifier to request fitment)
  modification      text not null,
  -- Human-friendly trim label (what we show in the UI)
  trim              text,
  created_at        timestamptz not null default now(),
  unique(vehicle_id, modification)
);

create index if not exists vehicle_mod_vehicle_idx on vehicle_modification(vehicle_id);

-- vehicle_fitment: allow multiple per vehicle (one per modification)
alter table vehicle_fitment
  add column if not exists vehicle_modification_id uuid references vehicle_modification(id) on delete cascade;

-- Drop old uniqueness constraint on vehicle_id (name is generated by Postgres)
do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conrelid = 'vehicle_fitment'::regclass
      and contype = 'u'
      and conname = 'vehicle_fitment_vehicle_id_key'
  ) then
    execute 'alter table vehicle_fitment drop constraint vehicle_fitment_vehicle_id_key';
  end if;
end $$;

alter table vehicle_fitment
  add constraint vehicle_fitment_vehicle_mod_uniq unique (vehicle_id, vehicle_modification_id);

-- OEM tire sizes should be per modification when provided
alter table vehicle_oem_tire_size
  add column if not exists vehicle_modification_id uuid references vehicle_modification(id) on delete cascade;

create index if not exists vehicle_oem_tire_size_mod_idx on vehicle_oem_tire_size(vehicle_modification_id);
